name: Run Tests on Push or Pull Request to Main

on:
  push:
    branches:
      - main  # Run tests on any push to the main branch
  pull_request:
    branches:
      - main  # Run tests on any pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Match your local Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          # Add project root to PYTHONPATH so imports work
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          # Run pytest and require 100% coverage
          pytest --cov=. --cov-fail-under=100
